namespace:
  name: staging 
 
service:
  port: 5111

image:
  repository: techtrends
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 3

resources:
  requests:
    cpu: 300m
    memory: 90Mi
  limits:
    cpu: 500m
    memory: 128Mi

configmap:
  data: "version: 1.18.0"
